# **NumPy (Numerical Python)**

Biblioteca fundamental para computação numérica em Python. O objeto principal é o __ndarray__ (n-dimensional array). 

## **Importação**

In [1]:
import numpy as np
print(f'Numpy version: {np.__version__}')

Numpy version: 1.21.5


## **Criação de Arrays**
### **A partir de listas Python**

In [2]:
lista_py = [1, 2, 3, 4, 5]
array_np = np.array(lista_py)
print(f'Array a partir de lista: {array_np}')
print((f'Tipo do array: {array_np.dtype}'))

lista_2d = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(lista_2d)
print(f'\nArray de 2 dimensões:\n{array_2d}')
print(f'Formato do array de 2 dimensões: {array_2d}') # (linhas, colunas)
print(f'Número de dimensões:{array_2d.ndim}')

Array a partir de lista: [1 2 3 4 5]
Tipo do array: int64

Array de 2 dimensões:
[[1 2 3]
 [4 5 6]]
Formato do array de 2 dimensões: [[1 2 3]
 [4 5 6]]
Número de dimensões:2


### **Arrays Especiais** 

In [3]:
# Array de zeros
zeros_array = np.zeros((2,3)) # Formato (2 linhas, 3 colunas)
print(f'Array de Zeros:\n{zeros_array}')

# Array de uns
ones_array = np.ones((3, 2), dtype=int)
print(f'\nArray de Uns(inteiros):\n{ones_array}')

# Array com um valor específico
full_array = np.full((2, 4), 7.5)
print(f'\nArray Preenchido com 7.5:\n{full_array}')

# Array identidade (quadrado)
identity_matrix = np.eye(3)
print(f'\nMatriz Identidade 3x3:\n{identity_matrix}')

Array de Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

Array de Uns(inteiros):
[[1 1]
 [1 1]
 [1 1]]

Array Preenchido com 7.5:
[[7.5 7.5 7.5 7.5]
 [7.5 7.5 7.5 7.5]]

Matriz Identidade 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# Array com sequência (similar a range)
arange_array = np.arange(0, 10, 2) # Ínicio, Parada(exclusiva), Passo
print(f'Array com arange: {arange_array}')

# Array com valores espaçados linearmente
linspace_array = np.linspace(0, 1, 5) # Ínicio, Parada(exclusiva), número de valores entre ínicio e fim(inclusive os dois) 
print(f'\nArray com linspace(0, 1, 5): {linspace_array}')

Array com arange: [0 2 4 6 8]

Array com linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


In [5]:
# Array aleatório [0, 1)
random_array = np.random.rand(2, 3)
print(f'Array Aleatório [0, 1):\n{random_array}')

# Array com valores aleatórios (distribuição normal padrão)
randn_array = np.random.randn(3, 2)
print(f'\nArray Aleatório Normal Padrão:\n{randn_array}')

# Array com inteiros aleatórios
randint_array = np.random.randint(1, 100, size=(2, 5)) # Formato 
print(f'\nArray com inteiros aleatórios:\n{randint_array}')

Array Aleatório [0, 1):
[[0.36641347 0.47591372 0.77730209]
 [0.41402154 0.79633171 0.27002365]]

Array Aleatório Normal Padrão:
[[ 0.44673866  0.76403325]
 [-0.25797407 -0.04333989]
 [-0.18401905  1.12312023]]

Array com inteiros aleatórios:
[[16 43 52 63 42]
 [95  9 48 52 72]]


## **Indexação e Fatiamento(Slicing)**
Similar a listas, mas com mais dimensões.

In [6]:
number = np.arange(10, 20)
print(f'Array original: = {number}')

# Acessando elementos 
print(f'Primeiro elemento: {number[0]}')
print(f'Último elemento: {number[0]}')

# Fatiamento
print(f'Do índice 2 ao 5 (exclusivo): {number[2:5]}')
print(f'Do ínico ao índice 4 (exclusivo): {number[:4]}')
print(f'Do índice 6 ao fim: {number[6:]}')
print(f'Com passo 2: {number[::2]}')

Array original: = [10 11 12 13 14 15 16 17 18 19]
Primeiro elemento: 10
Último elemento: 10
Do índice 2 ao 5 (exclusivo): [12 13 14]
Do ínico ao índice 4 (exclusivo): [10 11 12 13]
Do índice 6 ao fim: [16 17 18 19]
Com passo 2: [10 12 14 16 18]


In [7]:
# Fatiamento em arrays de 2 dimensões
numbers = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Arrray 2D Original:\n{numbers}')

# Elemento linha 1, coluna 2
print(f'Elemento numbers[1, 2]: {numbers[1, 2]}') # ou numbers[1][2]

# Primeira linha inteira
print(f'Primeira linha numbers[0, :]: {numbers[0, :]}') # ou numbers[0] 

# Segunda coluna inteira
print(f'Segunda coluna numbers[:, 1]:{numbers[:, 1]}')

Arrray 2D Original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Elemento numbers[1, 2]: 6
Primeira linha numbers[0, :]: [1 2 3]
Segunda coluna numbers[:, 1]:[2 5 8]


In [8]:
# Sub-array (linhas 0 e 1, colunas 1 e 2)
sub_array = numbers[0:2, 1:3]
print(f'Sub-array numbers[0:2, 1:3]:\n{sub_array}')

# IMPORTANTE: Fatias são "views" (visões) do array original.
# Modificar a fatia modifica o original!
sub_array[0, 0] = 99
print(f'Sub-array modificado:\n{sub_array}')
print(f'Sub-array modificado APÓS modificar a fatia')

# Para criar uma cópia independente, use .copy()
sub_array_copy = numbers[0:2, 1:3].copy()
sub_array_copy[0, 0] = 111
print(f'\nCópia modificada:\n{sub_array_copy}')
print(f'Array numbers original NÃO foi afetado pela cópia:\n{numbers}')

Sub-array numbers[0:2, 1:3]:
[[2 3]
 [5 6]]
Sub-array modificado:
[[99  3]
 [ 5  6]]
Sub-array modificado APÓS modificar a fatia

Cópia modificada:
[[111   3]
 [  5   6]]
Array numbers original NÃO foi afetado pela cópia:
[[ 1 99  3]
 [ 4  5  6]
 [ 7  8  9]]


## **Indexação Booleana**:
Selecionar elementos com base em condições.

In [9]:
data = np.random.randn(5, 3)
print(f'Dados aleatórios:\n{data}')

# Condição: elementos maiores que 0
condition = data > 0
print(f'\nMáscara booleana (data > 0):\n{condition}')

# Selecionar elementos que atendem à condicão
print(f'\nElementos maiores que 0: {data[condition]}')

# Combinar condições
data_col0 = data [:, 0]
print(f'\nPrimeira coluna: {data_col0}')
print(f'Elementos da col 0 > 0.5: {data_col0[data_col0 > 0.5]}')

# Selecionar linhas onde a primeira coluna é > 0
print(f'\nLinhas onde col 0 > 0:\n{data[data[:, 0] > 0]}')

# Selecionar linhas onde col 0 > 0 E col 1 < 0
linhas_selecionadas = data[(data[:,0] > 0) &  (data[:, 1 ] < 0)]
print(f'\nLinhas onde col 0 > 0 e col 1 < 0:\n{linhas_selecionadas}')

Dados aleatórios:
[[-0.29066888 -0.63835371 -1.15128164]
 [-0.63610217  0.57242107  0.57688543]
 [ 1.16235966 -0.74810098  0.29250556]
 [-0.84693022 -0.38704709 -0.63492681]
 [-1.09420484  0.58241229  2.41109553]]

Máscara booleana (data > 0):
[[False False False]
 [False  True  True]
 [ True False  True]
 [False False False]
 [False  True  True]]

Elementos maiores que 0: [0.57242107 0.57688543 1.16235966 0.29250556 0.58241229 2.41109553]

Primeira coluna: [-0.29066888 -0.63610217  1.16235966 -0.84693022 -1.09420484]
Elementos da col 0 > 0.5: [1.16235966]

Linhas onde col 0 > 0:
[[ 1.16235966 -0.74810098  0.29250556]]

Linhas onde col 0 > 0 e col 1 < 0:
[[ 1.16235966 -0.74810098  0.29250556]]


## **Operações Matemáticas Vetorizadas**
Operações elemento a elemento, muito mais rápidas que loops Python.

In [10]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print(f'Array x:\n{x}')
print(f'Array y:\n{y}')

# Soma elemento a elemento
print(f'\nSoma (x + y):\n{x + y}')
print(f'Soma (np.add(x, y)):\n{np.add(x, y)}')

# Subtração elemento a elemento
print(f'\nSubtração (x - y):\n{x - y}')
print(f'Subtração (np.subtract(x, y)):\n{np.subtract(x, y)}')

# Multiplicação elemento a elemento
print(f'\nMultiplicação (x * y):\n{x * y}')
print(f'\nMultiplicação (np.multiply(x, y)):\n{np.multiply(x, y)}')

Array x:
[[1 2]
 [3 4]]
Array y:
[[5 6]
 [7 8]]

Soma (x + y):
[[ 6  8]
 [10 12]]
Soma (np.add(x, y)):
[[ 6  8]
 [10 12]]

Subtração (x - y):
[[-4 -4]
 [-4 -4]]
Subtração (np.subtract(x, y)):
[[-4 -4]
 [-4 -4]]

Multiplicação (x * y):
[[ 5 12]
 [21 32]]

Multiplicação (np.multiply(x, y)):
[[ 5 12]
 [21 32]]


In [11]:
# Divisão elemento a elemento
print(f'Divisão (x / y):\n{x / y}')
print(f'\nDivisão (np.divide(x, y)):\n{np.divide(x, y)}')

# Multiplicação de Matrizes (produto escalar)
print(f'\nProduto Escalar (x @ y ou x.dot(y)):\n{x @ y}')
print(f'Produto Escalar (np.dot(x, y)):\n{np.dot(x, y)}')

# Raiz Quadradada
print(f'\nRaiz Quadrada (np.sqrt(x)):\n{np.sqrt(x)}')

# Exponencial (e^x)
print(f'Exponencial (np.exp(x)):\n{np.exp(x)}')


Divisão (x / y):
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

Divisão (np.divide(x, y)):
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

Produto Escalar (x @ y ou x.dot(y)):
[[19 22]
 [43 50]]
Produto Escalar (np.dot(x, y)):
[[19 22]
 [43 50]]

Raiz Quadrada (np.sqrt(x)):
[[1.         1.41421356]
 [1.73205081 2.        ]]
Exponencial (np.exp(x)):
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


## Funções Universais (unfuncs)
Funções que operam elemento a elemento.

In [12]:
arr = np.arange(5)
print(f'Array: {arr}')

print(f'Quadrado: {np.square(arr)}')
print(f'Logartimo natural: {np.log(arr + 1)}') # + 1 para evitar log(0)
print(f'Seno: {np.sin(arr)}')

# Funções binárias
arr1 = np.array([1, 5, 2, 8])
arr2 = np.array([4, 3, 6, 1])
print(f'Máximo elemento a elemento: {np.maximum(arr1, arr2)}')

Array: [0 1 2 3 4]
Quadrado: [ 0  1  4  9 16]
Logartimo natural: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Seno: [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
Máximo elemento a elemento: [4 5 6 8]


## Agregações (Reduções)
Calcular estatísticas sobre o array

In [13]:
data = np.random.randn(4, 3)
print(f'Dados:\n{data}')

# Soma de todos os elementos
print(f'\nSoma total: {data.sum()} ou {np.sum(data)}')

# Média de todos os elementos
print(f'Média total: {data.mean()} ou {np.mean(data)} ou ainda {data.sum()/data.size}')

# Soma ao longo das colunas (resultado por linha)
print(f'Soma por linha (axis=1): {data.sum(axis=1)}')

# Média ao longo das linhas (resultado por coluna)
print(f'Média por coluna (axis=0): {data.mean(axis=0)}')

# Desvio Padrão
print(f'Desvio Padrão total: {data.std()}')
print(f'Desvio Padrão por coluna (axis=0): {data.std(axis=0)}')

# Mínimo e Máximo
print(f'Valor mínimo: {data.min()}')
print(f'Valor máximo: {data.max()}')

# Índice do Mínimo e Máximo
print(f'Índice do mínimo global(flattend): {data.argmin()}')
print(f'Índice do máximo global(flattend): {data.argmax()}')
print(f'Índice dos máximos por coluna: {data.argmax(axis=0)} ')

Dados:
[[-1.49458845  0.85386969  0.29878914]
 [ 2.43642762 -1.20418938 -0.80151072]
 [-0.87211932 -2.21778184 -0.41131895]
 [-0.0765408  -1.94686146 -1.0935453 ]]

Soma total: -6.5293697693440755 ou -6.5293697693440755
Média total: -0.5441141474453396 ou -0.5441141474453396 ou ainda -0.5441141474453396
Soma por linha (axis=1): [-0.34192963  0.43072752 -3.50122011 -3.11694755]
Média por coluna (axis=0): [-0.00170524 -1.12874075 -0.50189646]
Desvio Padrão total: 1.2372150385075589
Desvio Padrão por coluna (axis=0): [1.4946917  1.20330468 0.52180426]
Valor mínimo: -2.217781841822748
Valor máximo: 2.4364276161606573
Índice do mínimo global(flattend): 7
Índice do máximo global(flattend): 3
Índice dos máximos por coluna: [1 0 0] 


## Broadcasting
Regras que permitem operações entre arrays de shapes diferentes

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([10, 20, 30]) # Formato (3, )

print(f'Array a (3x3):\n{a}')
print(f'Array b (3,):\n{b}')

# Somar b a cada linha de a
# b é "expandido" (broadcasted) para [[10, 20, 30], [10, 20, 30], [10, 20, 30]]
print(f'\nSoma a + b (broadcasting):\n{a + b}')

# Somar um escalar
print(f'\nSoma a + 100:\n{a + 100}')

c = np.array([[10], [20], [30]]) # Shape (3, 1)
print(f'\nArray c (3x1)\n{c}')

# Somar c a coluna de a 
# c é "expandido" para [[10, 10, 10], [20, 20, 20], [30, 30, 30]]
print(f'\nSoma de a + c (broadcasting):\n{a + c}')

Array a (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array b (3,):
[10 20 30]

Soma a + b (broadcasting):
[[11 22 33]
 [14 25 36]
 [17 28 39]]

Soma a + 100:
[[101 102 103]
 [104 105 106]
 [107 108 109]]

Array c (3x1)
[[10]
 [20]
 [30]]

Soma de a + c (broadcasting):
[[11 12 13]
 [24 25 26]
 [37 38 39]]


## Álgebra Linear
Funções comuns

In [15]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5], [6]])

print(f'Matriz A:\n{A}')
print(f'Vetor B:\n{B}')

# Transposta
print(f'\nTransposta de A:\n{A.T}')
print(f'Transposta de B:\n{B.T}')

# Inversa (apenas para matrizes quadradas invertíveis)
try:
    A_inv = np.linalg.inv(A)
    print(f'\nInversa de A:\n{A_inv}')
    # Verificação: A @ A_inv deve ser a identidade
    print(f'Verificação A @ A_inv:\n{np.round(A @ A_inv)}')
except np.linalg.LinAlgError:
    print('\nA não é invertível.')

# Determinante
print(f'\nDeterminante de A: {np.linalg.det(A)}')

# Resolver sistema linear Ax = B => x = A_inv @ B
try:
    x_sol = np.linalg.solve(A,B)
    print(f'\nSolução do sistema Ax=B:\n{x_sol}')
    # Verificação: A @ x_sol deve ser igual a B
    print(f'Verificação A @ x_sol:\n{A @ x_sol}')
except np.linalg.LinAlgError:
    print('\nNão foi possível resolver o sistema.')

# Autovalores e Autovetores
eigenvalues, eigenvectors = np.linalg.eig(A)
print(f'\nAutovalores de A: {eigenvalues}')

Matriz A:
[[1 2]
 [3 4]]
Vetor B:
[[5]
 [6]]

Transposta de A:
[[1 3]
 [2 4]]
Transposta de B:
[[5 6]]

Inversa de A:
[[-2.   1. ]
 [ 1.5 -0.5]]
Verificação A @ A_inv:
[[1. 0.]
 [0. 1.]]

Determinante de A: -2.0000000000000004

Solução do sistema Ax=B:
[[-4. ]
 [ 4.5]]
Verificação A @ x_sol:
[[5.]
 [6.]]

Autovalores de A: [-0.37228132  5.37228132]


### 🖇️ Links úteis/Referências
- 👉 [Documentação Principal](https://numpy.org/doc/stable/) 
- 👉 [Arrays (ndarray)](https://numpy.org/doc/stable/reference/arrays.ndarray.html) 
- 👉 [Operações Matemáticas](https://numpy.org/doc/stable/reference/routines.math.html) 
- 👉 [Indexação e Fatiamento](https://numpy.org/doc/stable/user/basics.indexing.html)