# NumPy (Numerical Python)

Biblioteca fundamental para computação numérica em Python. O objeto principal é o __ndarray__ (n-dimensional array). 

## Importação :

In [90]:
import numpy as np
print(f'Numpy version: {np.__version__}')

Numpy version: 1.21.5


## Criação de Arrays:
### A partir de listas Python:

In [91]:
lista_py = [1, 2, 3, 4, 5]
array_np = np.array(lista_py)
print(f'Array a partir de lista: {array_np}')
print((f'Tipo do array: {array_np.dtype}'))

lista_2d = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(lista_2d)
print(f'\nArray de 2 dimensões:\n{array_2d}')
print(f'Formato do array de 2 dimensões: {array_2d}') # (linhas, colunas)
print(f'Número de dimensões:{array_2d.ndim}')


Array a partir de lista: [1 2 3 4 5]
Tipo do array: int64

Array de 2 dimensões:
[[1 2 3]
 [4 5 6]]
Formato do array de 2 dimensões: [[1 2 3]
 [4 5 6]]
Número de dimensões:2


### Arrays Especiais 

In [92]:
# Array de zeros
zeros_array = np.zeros((2,3)) # Formato (2 linhas, 3 colunas)
print(f'\nArray de Zeros:\n{zeros_array}')

# Array de uns
ones_array = np.ones((3, 2), dtype=int)
print(f'\nArray de Uns(inteiros):\n{ones_array}')

# Array com um valor específico
full_array = np.full((2, 4), 7.5)
print(f'\nArray Preenchido com 7.5:\n{full_array}')

# Array identidade (quadrado)
identity_matrix = np.eye(3)
print(f'\nMatriz Identidade 3x3:\n{identity_matrix}')


Array de Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

Array de Uns(inteiros):
[[1 1]
 [1 1]
 [1 1]]

Array Preenchido com 7.5:
[[7.5 7.5 7.5 7.5]
 [7.5 7.5 7.5 7.5]]

Matriz Identidade 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [93]:
# Array com sequência (similar a range)
arange_array = np.arange(0, 10, 2) # Ínicio, Parada(exclusiva), Passo
print(f'\nArray com arange: {arange_array}')

# Array com valores espaçados linearmente
linspace_array = np.linspace(0, 1, 5) # Ínicio, Parada(exclusiva), número de valores entre ínicio e fim(inclusive os dois) 
print(f'\nArray com linspace(0, 1, 5): {linspace_array}')



Array com arange: [0 2 4 6 8]

Array com linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


In [94]:
# Array aleatório [0, 1)
random_array = np.random.rand(2, 3)
print(f'\nArray Aleatório [0, 1):\n{random_array}')

# Array com valores aleatórios (distribuição normal padrão)
randn_array = np.random.randn(3, 2)
print(f'\nArray Aleatório Normal Padrão:\n{randn_array}')

# Array com inteiros aleatórios
randint_array = np.random.randint(1, 100, size=(2, 5)) # Formato 
print(f'\nArray com inteiros aleatórios:\n{randint_array}')


Array Aleatório [0, 1):
[[0.92944011 0.511041   0.35788253]
 [0.53125368 0.76444059 0.43545912]]

Array Aleatório Normal Padrão:
[[-2.26822398  0.82786078]
 [-1.21004215  0.45707386]
 [ 0.56842402 -0.89948607]]

Array com inteiros aleatórios:
[[85 80  7 50  8]
 [53 20 82 19 84]]


## Indexação e Fatiamento(Slicing)
Similar a listas, mas com mais dimensões.

In [95]:
number = np.arange(10, 20)
print(f'\nArray original: = {number}')

# Acessando elementos 
print(f'Primeiro elemento: {number[0]}')
print(f'Último elemento: {number[0]}')

# Fatiamento
print(f'Do índice 2 ao 5 (exclusivo): {number[2:5]}')
print(f'Do ínico ao índice 4 (exclusivo): {number[:4]}')
print(f'Do índice 6 ao fim: {number[6:]}')
print(f'Com passo 2: {number[::2]}')


Array original: = [10 11 12 13 14 15 16 17 18 19]
Primeiro elemento: 10
Último elemento: 10
Do índice 2 ao 5 (exclusivo): [12 13 14]
Do ínico ao índice 4 (exclusivo): [10 11 12 13]
Do índice 6 ao fim: [16 17 18 19]
Com passo 2: [10 12 14 16 18]


In [96]:
# Fatiamento em arrays de 2 dimensões
numbers = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'\nArrray 2D Original:\n{numbers}')

# Elemento linha 1, coluna 2
print(f'Elemento numbers[1, 2]: {numbers[1, 2]}') # ou numbers[1][2]

# Primeira linha inteira
print(f'Primeira linha numbers[0, :]: {numbers[0, :]}') # ou numbers[0] 

# Segunda coluna inteira
print(f'Segunda coluna numbers[:, 1]:{numbers[:, 1]}')



Arrray 2D Original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Elemento numbers[1, 2]: 6
Primeira linha numbers[0, :]: [1 2 3]
Segunda coluna numbers[:, 1]:[2 5 8]


In [ ]:
# Sub-array (linhas 0 e 1, colunas 1 e 2)
sub_array = numbers[0:2, 1:3]
print(f'Sub-array numbers[0:2, 1:3]: {sub_array}')

# IMPORTANTE: Fatias são "views" (visões) do array original.
# Modificar a fatia modifica o original!
sub_array[0, 0] = 99
print(f'Sub-array modificado:\n{sub_array}')
print(f'Sub-array modificado APÓS modificar a fatia')

# Para criar uma cópia independente, use .copy()
sub_array_copy = numbers[0:2, 1:3].copy()
sub_array_copy[0, 0] = 111
print(f'\nCópia modificada:\n{sub_array_copy}')
print(f'Array numbers original NÃO foi afetado pela cópia:\n{numbers}')


Sub-array numbers[0:2, 1:3]: [[2 3]
 [5 6]]
Sub-array modificado:
[[99  3]
 [ 5  6]]
Sub-array modificado APÓS modificar a fatia

Cópia modificada:
[[111   3]
 [  5   6]]
Array number original NÃO foi afetado pela cópia:
[[ 1 99  3]
 [ 4  5  6]
 [ 7  8  9]]


## **Indexação Booleana**:
Selecionar elementos com base em condições.